### ISSUE TITLE
It doesn't find the game files

### ISSUE THREAD

**Issue by JustRoby0** [akusei/suffer2gether#1]
The title says it all..

**Comment by akusei** [comment]
Just tested it on a new Green Hell install through steam and it detects them on my system. I'll take a look at the code but could you answer the following:

1. What version of windows are you running?
2. Was the game installed through Steam?
3. Is it a pirated copy of Green Hell?

**Comment by Kuxerin** [comment]
The patch works well. The problem is that when the game is not installed (for example copied from a removable drive or downloaded as an archive) a registry entry is not generated, thus the patch does not find the install location in the registry (obviously).

_[I got this issue because I mostly copy games for my friend who does not have a good bandwidth to download huge size games in a bearable time limit.]_

**Comment by akusei** [comment]
Perfect, thank you for the extra information. I'll add a dialog to browse
to your game files if it can't detect them

**Comment by Kuxerin** [comment]
You are welcome. Thank you for your work, I really appreciate it.
_(Even if I sorted out this problem by manually adding the path to the registry)_
